import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

interface ProjectCategory {
    id: number
    code: string
    description: string
}

interface ProjectCategoryApiResponse {
    ok: boolean,
    message: string,
    projectCategories: ProjectCategory[]
}

export const projectCategoryApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: `${import.meta.env.VITE_BACKEND_ROOT_URL}/project-categories`}),
  reducerPath: "projectCategoriesApi",
  //Used for caching and invalidation.
  tagTypes: ["ProjectCategories"],
  endpoints: build => ({
    getProjectCategories: build.query<ProjectCategoryApiResponse, void>({
      query: () => '/',
    }),
  }),
})

// Hooks are auto-generated by RTK-Query
export const { useGetProjectCategoriesQuery } = projectCategoryApiSlice;